### PR TITLE
Update meta.yaml

### PR DESCRIPTION
**Pull request by EnricoRiccardi**
version 1released!

We updated the pypi and released this version that is going to be the main one for quite some time.

### CODE REVIEW

**Comment by synapticarbors** [comment]
@EnricoRiccardi -- now that the tests have all passed, you can merge this PR which will trigger the CI to push the new release to anaconda.org so that they are available via conda.

**Comment by EnricoRiccardi** [comment]
I can just ask for a merge request, (which I did here), right?

**Comment by synapticarbors** [comment]
You followed the correct procedure -- fork this feedstock and make a pull request from that fork. As a co-maintainer of this recipe and feedstock, you should be able to merge your own pull request. If you ever have any questions about a PR on this feedstock, you can always ping someone from the conda-forge organization or ask on the conda-forge gitter chat (gitter.im/conda-forge/conda-forge.github.io), but otherwise you have full control over updating and maintaining this feedstock.

**Comment by EnricoRiccardi** [comment]
I did try countless times what you suggested, I always come back here.

**Comment by synapticarbors** [comment]
You should have permission to merge this pull request. Do you not see the option to do so?

**Comment by EnricoRiccardi** [comment]
no I don't. I can just Comment, Close and comment, and it writes me that *
EnricoRiccardi wants to merge 1 commit into conda-forge:master from EnricoRiccardi:master

**Comment by synapticarbors** [comment]
Ok, I see the problem. No one was assigned to the `pyretis` team:

https://github.com/orgs/conda-forge/teams/pyretis/members

@jakirkham, @ocefpaf do you know how to resolve this?

**Comment by EnricoRiccardi** [comment]
ok, now it works! The problem is that conda-forge invited me to be part of the conda-forge team, but this notification didn't show up anywhere!!! Come on! @jakirkham, @ocefpaf  that is a system bug or? By complete randomness I found it now (and thank to you too)!

**Comment by ocefpaf** [comment]
It probably went to your spam e-mail .There is nothing we can do about it. GitHub now forbids to add people to teams without that e-mail invitation.

**Comment by EnricoRiccardi** [comment]
Yes, I found it now in the spam.. But maybe a notification here? Since I am the author of the package, wouldn't that be the default to be in the team of the package? 

nevermind for me now since it has been solved...

**Comment by ocefpaf** [comment]
You can raise that concern with GitHub. There is nothing we can do about it.
If you think about it that policy makes perfect sense, otherwise anyone could add people programatically to dozens of repos without that person consent.

**Comment by jakirkham** [comment]
> But maybe a notification here?

That has been raised before ( https://github.com/conda-forge/conda-forge-webservices/issues/73 ). Unfortunately no one has had time to do it (after all we are all volunteers here). Should be simple if someone wants to try. 😉

> Since I am the author of the package, wouldn't that be the default to be in the team of the package?

Not for the first one. GitHub wants to check that you are ok joining `conda-forge`. As @ocefpaf said, there is nothing we can do about this.

Fortunately GitHub streamlines all subsequent team additions. So later recipes you add should just automatically add you to those teams (as you will already be a member of this org).

**Comment by EnricoRiccardi** [comment]
thanks for the answers ! :)

**Pull request merged**
